export const FETCH_USER_RECIPES = 'FETCH_USER_RECIPES';
export const FETCH_ADMIN_RECIPES = 'FETCH_ADMIN_RECIPES';
export const ADD_USER_RECIPE = 'ADD_USER_RECIPE';
export const SEARCH_USER_RECIPE = 'SEARCH_USER_RECIPE';
export const ADD_ADMIN_RECIPE = 'ADD_ADMIN_RECIPE';
export const APPROVE_PENDING_DATA = 'APPROVE_PENDING_DATA';
export const REMOVE_USER_RECIPE = 'REMOVE_USER_RECIPE';
export const ADD_ADMIN_COMMENT = 'ADD_ADMIN_COMMENT';